In [19]:
"""
    需求： 绘制 矩形，圆形
    想要绘制 多条线段，直接在 继续调用 line()方法
"""
import cv2
import numpy as np

# 自定义一个 图片的大小和深度【规定图片的维度】
newImageInfo = (500,500,3)

# 初始化一个 全0矩阵
dst = np.zeros(newImageInfo,np.uint8)

# 绘制 一个矩形
# 参数1：目标图片数据， 参数2：左上角的点坐标， 参数3：右下角的点坐标， 参数4：颜色， 
# 参数5：表示 是否对矩形框内填充 取值： 全部填充：-1， 0或不写：不填充  如果 > 0 ，代表线条 线条宽度
cv2.rectangle(dst,(50,100),(200,300),(255,0,0),20)


# 绘制 一个圆形
# 参数1：目标图片数据， 参数2：圆心位置坐标， 参数3：圆半径， 参数4：颜色， 参数5： 是否填充fill
cv2.circle(dst,(250,250),50,(0,255,0),5)


# 绘制一个椭圆（圆弧）
# 参数1： 目标图片数据，参数2：椭圆圆心坐标， 参数3：轴长，一个表示长轴，一个表示短轴， 参数4：椭圆偏转角度，
# 参数5： 起始角度
# 参数6： 终止角度 范围： 180：表只 绘制180的 即一半， 360：表 绘制360度 即全部
# 参数7： 颜色， 参数8：是否填充
cv2.ellipse(dst,(280,280),(150,100),0,180,360,(255,255,0),0)


# 绘制一个任意多边形
points = np.array([[150,50],[140,140],[200,170],[250,250],[150,50]])  # 先定义 多边形 的 每个点坐标
print(points.shape)
points = points.reshape((-1,1,2)) # 转换 矩阵维度
print(points.shape)

# 绘制 多边形
# 参数1：目标图片数据， 参数2：多边形各个点 的矩阵， 参数3：是否闭合， True：表示闭合，形成多边形， False：表示不闭合，则形成 折线
# 参数4：颜色， 参数5：是否填充fill
cv2.polylines(dst,np.int32([points]),True,(0,255,255),5) 

cv2.imshow("dst",dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

(5, 2)
(5, 1, 2)


In [25]:
""" 备注"""
import cv2
import numpy as np

# 自定义一个 图片的大小和深度【规定图片的维度】
newImageInfo = (500,500,3)


# 初始化一个 全0矩阵
dst = np.zeros(newImageInfo,np.uint8)

# 绘制一个任意多边形
points = np.array([[150,50],[140,140],[200,170],[250,250],[150,400]],np.int32) # 这里要用 np.int32，不能用np.uint8, 可能由于opencv版本是3.4.*
print(points.shape)
points = points.reshape((-1,1,2)) # 进行 维度转换 
print(points.shape)
print(points)
# cv2.polylines(dst,np.int32([points]),True,(0,255,255),5)
cv2.polylines(dst,[points],True,(0,255,255),2)

cv2.imshow("dst",dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

(5, 2)
(5, 1, 2)
[[[150  50]]

 [[140 140]]

 [[200 170]]

 [[250 250]]

 [[150 400]]]
